### ISSUE TITLE
x = x.permute(0,2,1,3,4) 能解释一下这么做的原因是什么吗，好难理解

### ISSUE THREAD

**Issue by qianjinhao** [Zvenger/VPReID_baseline#1]
https://github.com/Zvenger/VPReID_baseline/blob/e8d398d7c61104b30686639435d20070294b844c/net/models.py#L60

**Comment by Zvenger** [comment]
这里交换维度是把baseline里的交换维度，再换回来，为了后面x= x.view(b,c,t,h,w)的特征分组操作。

baseline里把 b,t,c,h,w 换成 b,c,t,h,w为了后面的AdaptiveAvgPool3d(1)。但是我要进行特征分组操作，就把b,c,t,h,w换成原先的b,t,c,h,w再x= x.view(b,c,t,h,w)特征分组成新的特征表示。

如果把60行和61行的代码都注释掉，就是正常的逐帧BDB操作，这个操作R1提升有限，和baseline比提升在3%左右，R1大概在91左右，而我进行了特征分组后R1可以提升7%在95左右。

特征分组为什么有效，随机擦除特征过程到底有什么含义，就不是很清楚了。

我之前发知乎上的文章希望和同样是研究VPReID的人一起讨论下，但是现在并没有人和我一起讨论研究。另外这个应该算是个trick，基本每个方法都可以在通过backbone（如resnet50 ）后先加这个方法。但是是否一定有效就不知道了。

**Comment by Zvenger** [comment]
上面提的R1的提升，都是在MARS上做的实验。

**Comment by qianjinhao** [comment]
> 这里交换维度是把baseline里的交换维度，再换回来，为了后面x= x.view(b,c,t,h,w)的特征分组操作。
> 
> baseline里把 b,t,c,h,w 换成 b,c,t,h,w为了后面的AdaptiveAvgPool3d(1)。但是我要进行特征分组操作，就把b,c,t,h,w换成原先的b,t,c,h,w再x= x.view(b,c,t,h,w)特征分组成新的特征表示。
> 
> 如果把60行和61行的代码都注释掉，就是正常的逐帧BDB操作，这个操作R1提升有限，和baseline比提升在3%左右，R1大概在91左右，而我进行了特征分组后R1可以提升7%在95左右。
> 
> 特征分组为什么有效，随机擦除特征过程到底有什么含义，就不是很清楚了。
> 
> 我之前发知乎上的文章希望和同样是研究VPReID的人一起讨论下，但是现在并没有人和我一起讨论研究。另外这个应该算是个trick，基本每个方法都可以在通过backbone（如resnet50 ）后先加这个方法。但是是否一定有效就不知道了。

我正在跑你的代码基本所得结果和你说的一致。我也是研究video-base reid，我知乎私信你加你微信吧

**Comment by Zvenger** [comment]
好的
